mm_regime_banner_index:
  path: /
  methods : GET
  defaults:
    _controller: Hp\Regimebanner\Controller\AdminBannerRegimeController::indexAction
    _disable_module_prefix: true
    _legacy_controller : AdminBannerRegimeController
    _legacy_link: AdminBannerRegimeController

mm_regime_banner_create:
  path: /create
  methods : [GET,POST]
  defaults:
    _controller: Hp\Regimebanner\Controller\AdminBannerRegimeController::createAction
    _disable_module_prefix: true
    _legacy_controller : AdminBannerRegimeController
    _legacy_link: AdminBannerRegimeController

mm_regime_banner_edit:
  path: /edit/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Regimebanner\Controller\AdminBannerRegimeController::editAction
    _disable_module_prefix: true
    _legacy_controller : AdminBannerRegimeController
    _legacy_link: AdminBannerRegimeController
mm_regime_banner_delete:
  path: /delete/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Regimebanner\Controller\AdminBannerRegimeController::deleteAction
    _disable_module_prefix: true
    _legacy_controller : AdminBannerRegimeController
    _legacy_link: AdminBannerRegimeController
mm_regime_banner_active:
  path: /active/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Regimebanner\Controller\AdminBannerRegimeController::activeAction
    _disable_module_prefix: true
    _legacy_controller : AdminBannerRegimeController
    _legacy_link: AdminBannerRegimeController
