mm_product_brand_index:
  path: /
  methods: [GET]
  defaults:
    _controller: Hp\Brandproducts\Controller\BrandProductController::indexAction
    _disable_module_prefix: true
    _legacy_controller: BrandProductController
    _legacy_link: BrandProductController

mm_product_brand_create:
  path: /create
  methods: [GET,POST]
  defaults:
    _controller: Hp\Brandproducts\Controller\BrandProductController::createAction
    _disable_module_prefix: true
    _legacy_controller: BrandProductController
    _legacy_link: BrandProductController

mm_product_brand_edit:
  path: /edit/{id}
  methods: [GET,POST]
  defaults:
    _controller: Hp\Brandproducts\Controller\BrandProductController::editAction
    _disable_module_prefix: true
    _legacy_controller: BrandProductController
    _legacy_link: BrandProductController

mm_product_brand_delete:
  path: /delete/{id}
  methods: [GET,POST]
  defaults:
    _controller: Hp\Brandproducts\Controller\BrandProductController::deleteAction
    _disable_module_prefix: true
    _legacy_controller: BrandProductController
    _legacy_link: BrandProductController

