mm_banners_index:
  path: /
  methods : GET
  defaults:
    _controller: Hp\Mmbanners\Controller\BannerController::indexAction
    _disable_module_prefix: true
    _legacy_controller : BannerController
    _legacy_link: BannerController

mm_banners_create:
  path: /create/
  methods : [GET,POST]
  defaults:
    _controller: Hp\Mmbanners\Controller\BannerController::createAction
    _disable_module_prefix: true
    _legacy_controller : BannerController
    _legacy_link: BannerController

mm_banners_edit:
  path: /edit/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Mmbanners\Controller\BannerController::editAction
    _disable_module_prefix: true
    _legacy_controller : BannerController
    _legacy_link: BannerController

mm_banners_delete:
  path: /delete/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Mmbanners\Controller\BannerController::deleteAction
    _disable_module_prefix: true
    _legacy_controller : BannerController
    _legacy_link: BannerController

mm_banners_active:
  path: /active/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Mmbanners\Controller\BannerController::activeAction
    _disable_module_prefix: true
    _legacy_controller : BannerController
    _legacy_link: BannerController