mm_brand_banners_index:
  path: /
  methods : GET
  defaults:
    _controller: Hp\Mmbrandbanner\Controller\AdminBrandController::indexAction
    _disable_module_prefix: true
    _legacy_controller : AdminBrandController
    _legacy_link: AdminBrandController

mm_brand_banners_create:
  path: /create/
  methods : [GET,POST]
  defaults:
    _controller: Hp\Mmbrandbanner\Controller\AdminBrandController::createAction
    _disable_module_prefix: true
    _legacy_controller : AdminBrandController
    _legacy_link: AdminBrandController

mm_brand_banners_edit:
  path: /edit/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Mmbrandbanner\Controller\AdminBrandController::editAction
    _disable_module_prefix: true
    _legacy_controller : AdminBrandController
    _legacy_link: AdminBrandController

mm_brand_banners_delete:
  path: /delete/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Mmbrandbanner\Controller\AdminBrandController::deleteAction
    _disable_module_prefix: true
    _legacy_controller : AdminBrandController
    _legacy_link: AdminBrandController

mm_brand_banners_active:
  path: /active/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Mmbrandbanner\Controller\AdminBrandController::activeAction
    _disable_module_prefix: true
    _legacy_controller : AdminBrandController
    _legacy_link: AdminBrandController
