mm_atout_banner_index:
  path: /
  methods : GET
  defaults:
    _controller: Hp\Nosatouts\Controller\AdminNosAtoutController::indexAction
    _disable_module_prefix: true
    _legacy_controller : AdminNosAtoutController
    _legacy_link: AdminNosAtoutController

mm_atout_banner_create:
  path: /create
  methods : [GET,POST]
  defaults:
    _controller: Hp\Nosatouts\Controller\AdminNosAtoutController::createAction
    _disable_module_prefix: true
    _legacy_controller : AdminNosAtoutController
    _legacy_link: AdminNosAtoutController

mm_atout_banner_edit:
  path: /edit/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Nosatouts\Controller\AdminNosAtoutController::editAction
    _disable_module_prefix: true
    _legacy_controller : AdminNosAtoutController
    _legacy_link: AdminNosAtoutController
mm_atout_banner_delete:
  path: /delete/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Nosatouts\Controller\AdminNosAtoutController::deleteAction
    _disable_module_prefix: true
    _legacy_controller : AdminNosAtoutController
    _legacy_link: AdminNosAtoutController
mm_atout_banner_active:
  path: /active/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Nosatouts\Controller\AdminNosAtoutController::activeAction
    _disable_module_prefix: true
    _legacy_controller : AdminNosAtoutController
    _legacy_link: AdminNosAtoutController
