mm_testimonial_index:
  path: /
  methods : [GET]
  defaults:
    _controller: Hp\Testimonial\Controller\AdminTestomonial::indexAction
    _disable_module_prefix: true
    _legacy_controller : AdminTestomonial
    _legacy_link: AdminTestomonial


mm_testimonial_create:
  path: /create
  methods : [GET,POST]
  defaults:
    _controller: Hp\Testimonial\Controller\AdminTestomonial::createAction
    _disable_module_prefix: true
    _legacy_controller : AdminTestomonial
    _legacy_link: AdminTestomonial


mm_testimonial_edit:
  path: /edit/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Testimonial\Controller\AdminTestomonial::indexAction
    _disable_module_prefix: true
    _legacy_controller : AdminTestomonial
    _legacy_link: AdminTestomonial

mm_testimonial_delete:
  path: /delete/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\Testimonial\Controller\AdminTestomonial::indexAction
    _disable_module_prefix: true
    _legacy_controller : AdminTestomonial
    _legacy_link: AdminTestomonial

