mm_flash_banners_index:
  path: /
  methods : GET
  defaults:
    _controller: Hp\MmFlashBanner\Controller\AdminFlashBanner::indexAction
    _disable_module_prefix: true
    _legacy_controller : AdminFlashBanner
    _legacy_link: AdminFlashBanner

mm_flash_banners_create:
  path: /create/
  methods : [GET,POST]
  defaults:
    _controller: Hp\MmFlashBanner\Controller\AdminFlashBanner::createAction
    _disable_module_prefix: true
    _legacy_controller : AdminFlashBanner
    _legacy_link: AdminFlashBanner

mm_flash_banners_edit:
  path: /edit/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\MmFlashBanner\Controller\AdminFlashBanner::editAction
    _disable_module_prefix: true
    _legacy_controller : AdminFlashBanner
    _legacy_link: AdminFlashBanner

mm_flash_banners_delete:
  path: /delete/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\MmFlashBanner\Controller\AdminFlashBanner::deleteAction
    _disable_module_prefix: true
    _legacy_controller : AdminFlashBanner
    _legacy_link: AdminFlashBanner

mm_flash_banners_active:
  path: /active/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\MmFlashBanner\Controller\AdminFlashBanner::activeAction
    _disable_module_prefix: true
    _legacy_controller : AdminFlashBanner
    _legacy_link: AdminFlashBanner

mm_flash_banners_header_edit:
  path: /header/{id}
  methods : [GET,POST]
  defaults:
    _controller: Hp\MmFlashBanner\Controller\AdminFlashBanner::editHeaderAction
    _disable_module_prefix: true
    _legacy_controller : AdminFlashBanner
    _legacy_link: AdminFlashBanner