services:
  testimonial.grid.definition.factory:
    public: true
    class: 'Hp\Testimonial\Grid\Definition\Factory\TestimonialGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

  testimonial.grid.query_builder:
    public: true
    class: 'Hp\Testimonial\Grid\Query\TestimonialQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'

  testimonial.grid.data.factory:
    public: true
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@testimonial.grid.query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'Testimonial'

  testimonial.grid.data.factory.doctrine:
    public: true
    class: 'Hp\Testimonial\Grid\Data\Factory\TestimonialGridDataFactory'
    arguments:
      - '@testimonial.grid.data.factory'              

  testimonial.grid.grid_factory:
    public: true
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@testimonial.grid.definition.factory'
      - '@testimonial.grid.data.factory.doctrine'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  #Form
  testimonial.form.identifiable_object.builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    public: true
    arguments:
        - 'Hp\Testimonial\Form\TestimonialType'
        - '@testimonial.form.identifiable_object.data_provider'

  testimonial.form.identifiable_object.data_provider:
    class: Hp\Testimonial\Form\Provider\TestimonialDataProvider